version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
  test1:
    working_directory: ~/
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn install
  test2:
    working_directory: ~/
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test1
      - test2
