version: 2
jobs:
  build:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
  install:
   working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn install
  test:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - install
      - test
