version: 2
jobs:
  build:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
  restore_cache:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  install:
   working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn install
  save_cache:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  test:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - restore_cache
      - install
      - save_cache
      - test
