version: 2
jobs:
  build:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
  cache1:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
  test1:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn install
  cache2:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test2:
    working_directory: ~/electron-antd-demo
    docker:
      - image: circleci/node:7.10
    steps:
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cache1
      - test1
      - cache2
      - test2
